---

- name: Ensure expected distribution
  assert:
    that: ansible_os_family == "RedHat"

# De-registering and then registering is equivalent to using the
# `force_register` argument, which was added in Ansible 2.2. We use this
# technique to preserve compatibility with RHEL 6.
- name: subscription-manager de-register
  redhat_subscription:
    state: absent
  when: >
    ansible_distribution == "RedHat" and
    rhn_pool is defined and
    (rhn_username is defined and rhn_password is defined) or
    (rhn_activation_key is defined and rhn_organization is defined)

- name: subscription-manager register and subscribe by username and password
  redhat_subscription:
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
    pool: "{{ rhn_pool }}"  # e.g. rhn_pool='^SKU Name$'
  when:
    - ansible_distribution == "RedHat"
    - rhn_pool is defined
    - rhn_username is defined
    - rhn_password is defined
    - rhn_activation_key is undefined
    - rhn_organization is undefined

- name: subscription-manager register and subscribe by activation key
  redhat_subscription:
    activationkey: "{{ rhn_activation_key }}"
    org_id: "{{ rhn_organization }}"
    pool: "{{ rhn_pool }}"
  when:
    - ansible_distribution == "RedHat"
    - rhn_pool is defined
    - rhn_username is undefined
    - rhn_password is undefined
    - rhn_activation_key is defined
    - rhn_organization is defined

- name: Subscription Manager disable all repositories
  shell: "subscription-manager repos --disable \"*\""
  when: ansible_distribution == "RedHat"

- name: Enable main repository
  shell: "subscription-manager repos --enable rhel-{{ ansible_distribution_major_version }}-server-rpms"
  when: ansible_distribution == "RedHat"

- name: Enable optional repository
  shell: "subscription-manager repos --enable rhel-{{ ansible_distribution_major_version }}-server-optional-rpms"
  when: ansible_distribution == "RedHat"

- name: Enable extras repository
  shell: "subscription-manager repos --enable rhel-{{ ansible_distribution_major_version }}-server-extras-rpms"
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version|int >= 7

- name: Enable atomic host repository
  shell: "subscription-manager repos --enable rhel-atomic-host-rpms"
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version|int >= 7

- name: Enable EPEL repository
  action: "{{ ansible_pkg_mgr }} name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
  when: ansible_distribution == "RedHat"

- name: Open firewall ports (iptables)
  iptables:
    action: insert
    chain: INPUT
    ctstate: NEW
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.port }}"
    jump: ACCEPT
  with_items:
    - { port: 'http', protocol: 'tcp' }
    - { port: 'https', protocol: 'tcp' }
    - { port: 'amqps', protocol: 'tcp' }
    - { port: 'amqp', protocol: 'tcp' }
  when:
    - pulp_install_prerequisites
    - ansible_distribution == "RedHat" and ansible_distribution_major_version|int == 6
  notify:
    - Save IPv4 iptables configuration

- block:
  - name: Install firewalld and python bindings
    action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
    with_items:
      - firewalld
      - python-firewall

  - name: Start and enable firewalld
    service: name=firewalld state=started enabled=yes

  - name: Open firewall ports (firewalld)
    firewalld:
      port: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true
    with_items:
      # As of this writing, firewalld knows about a miniscule number of services
      # out of the box. `firewall-cmd --get-services | wc -w` returns "103", and
      # the list of services doesn't include amqp or amqps, among many others.
      # Thus, we have to explicitly write out port/transport pairs here.
      - "80/tcp"   # http
      - "443/tcp"  # https
      - "5671/tcp" # amqps
      - "5672/tcp" # amqp

  when:
    - pulp_install_prerequisites
    - not (ansible_distribution == "RedHat" and ansible_distribution_major_version|int == 6)

- include: pulp_server.yaml
  when: pulp_install_server
